feature: cli command to regenerate files
pluginsGLPI/fields pull request #586
Opened 2022-11-03 03:00 UTC by po1vo

subj.

2022-11-03 07:16 UTC, stonebuzz commented
Can you create a subdirectory ```command``` in the ```inc``` directory and place the new file there
Best regards

2022-11-03 07:31 UTC, stonebuzz commented
For ```Lint```
Can you run this command (at root folder of plugin) 
```shell
../../vendor/bin/licence-headers-check --ansi --no-interaction --directory="." -f
```
this should add the missing header to the new file

2022-11-03 11:19 UTC, po1vo commented
@stonebuzz , done.

2022-11-04 07:40 UTC, stonebuzz requested changes

2022-11-04 07:40 UTC, stonebuzz commented on inc/command/regeneratefilescommand.class.php
> +            __('Check all stored containers files (classes & front) are present and create them if needed', 'fields')
```suggestion
            __('Clean up all files generated by the plugin (classes & front) and  regenerate it', 'fields')
```

2022-11-04 13:50 UTC, stonebuzz approved these changes

2022-11-16 07:58 UTC, cedric-anne commented on inc/command/regeneratefilescommand.class.php
> +        );
```suggestion
        $this->setHelp(
            __('This command will clean up all files generated by the plugin and regenerate them.', 'fields')
        );
```

2022-11-16 07:58 UTC, cedric-anne commented on inc/command/regeneratefilescommand.class.php
> +        $this->setDescription(__('Regenerate container files.', 'fields'));
```suggestion
        $this->setDescription(__('Regenerates containers files.', 'fields'));
```

2022-11-16 07:59 UTC, cedric-anne approved these changes

2022-11-16 08:00 UTC, merged