Fix(Container): deactivate domtab that no longer works and stop offer…
pluginsGLPI/fields pull request #741
Opened 2023-12-15 10:36 UTC by stonebuzz

Since GLPI 10

```Ticket``` ```Solution``` tab no longer exist
```Problem``` ```Solution``` tab no longer exist
```Change``` ```Analysis``` / ```Solution``` / ```Plans``` no longer exist

So, deactivate related ```container``` (with type ```Insertion in the form of a specific tab (before save button)```) and remove the ability to create containers on these tabs (tabs on ```Entity``` are maintained as they are still functional))

**Release note should mention this :**

Adding a container (with type ```Insertion in the form of a specific tab (before save button)```) to the following tabs is no longer possible (as it no longer works since version 10)
- Change -> analysis
- Change -> plans
- Change -> solution
- Ticket -> solution
- Problem -> solution

All related container have been deactivated

For the ```Solution```, it is now possible to add a block on ITILSolution, only for the "Insertion in the form (before save button)" type.

**IMPORTANT**
no migration proposed from the old type to the new one, 
as it hasn't worked for a while, I don't suppose anyone has added a block 
and required lot of work

 
Fix : 
https://github.com/pluginsGLPI/fields/issues/737
https://github.com/pluginsGLPI/fields/issues/407 
https://github.com/pluginsGLPI/fields/issues/599 
https://github.com/pluginsGLPI/fields/issues/456

2024-01-03 19:20 UTC, Apashh commented
Hello,

If i understand, now its not possible to add a field on solution ? Like this ?
![image](https://github.com/pluginsGLPI/fields/assets/83477029/68915844-fced-499a-9e4b-c6731139ae08)

A solution have been created : https://github.com/pluginsGLPI/fields/pull/612
But not work

Can you explain your branch and your code ? What is the solution to use a field before send solution ?

Thanks !

2024-01-08 08:56 UTC, stonebuzz commented
> For the `Solution`, it is now possible to add a block on ITILSolution, only for the "Insertion in the form (before save button)" type.


For the Solution, it is now possible to add a block on ITILSolution, only for the "Insertion in the form (before save button)" type.

2024-01-08 18:28 UTC, Apashh commented
> > For the `Solution`, it is now possible to add a block on ITILSolution, only for the "Insertion in the form (before save button)" type.
> 
> 
> 
> 
> 
> For the Solution, it is now possible to add a block on ITILSolution, only for the "Insertion in the form (before save button)" type.
> 
> 
> 
> 

Okay its not a good solution, it will be better to add field directely on solution reply.. So shame...

2024-02-21 09:47 UTC, Rom1-B requested changes

2024-02-21 09:47 UTC, Rom1-B commented on inc/container.class.php
> +        //Problem Solution tab no longer exist exist disable it
```suggestion
        //Ticket Solution tab no longer exist disable it
        //Problem Solution tab no longer exist disable it
```

2024-02-21 09:55 UTC, Rom1-B approved these changes

2024-02-21 10:59 UTC, AdrienClairembault approved these changes

2024-02-21 10:59 UTC, merged