fix(SearchOption): Fix search on multiple dropdown
pluginsGLPI/fields pull request #754
Opened 2024-01-31 09:03 UTC by stonebuzz

Fix search on multiple dropdown

Actually, ```multiple dropdown``` only use ```contain``` / ```not contain``` ```searchtype```.

SQL query is computed with ```=``` on column that contain ```['ID', 'ID, 'ID']``` and try to match ```string```

Use of ```plugin_fields_addWhere``` to replace ```=``` by ```like``` when related field is from plugin ```fields``` and when it's ```multiple```

Use of ```getSpecificValueToSelect``` to display a ```real``` dropdown.

Force ```'equals', 'notequals'``` ```searchtype```

2024-02-01 08:38 UTC, stonebuzz commented on hook.php
> +        return $link . " `$table" . "_" . "$field`" . "." . "`$field` LIKE '%$val%'";
done with 07d4661

2024-02-01 08:43 UTC, stonebuzz commented on hook.php
> +        return $link . " `$table" . "_" . "$field`" . "." . "`$field` LIKE '%$val%'";
done with [1279dea](https://github.com/pluginsGLPI/fields/pull/754/commits/1279dea0c3849fb98a9edcec47d594b644752880)

2024-02-01 08:45 UTC, stonebuzz commented on hook.php
> +        return $link . " `$table" . "_" . "$field`" . "." . "`$field` LIKE '%$val%'";
I don't think, search on ```["2"]``` should not work on ```["2", "3", "54"]```

2024-02-01 17:07 UTC, AdrienClairembault requested changes
Does not seems to work on my side.

Here is my dropdown:

![image](https://github.com/pluginsGLPI/fields/assets/42734840/27af0458-d3fe-423c-aab2-34613abdae33)

The field works fine in a ticket;

![image](https://github.com/pluginsGLPI/fields/assets/42734840/493b9e12-8e00-40d7-ae8d-954dc2767f92)

But I don't have the correct search operators:

![image](https://github.com/pluginsGLPI/fields/assets/42734840/f9196bdc-2df8-4392-806f-72122278fe8c)

Am I missing something ?

2024-02-02 07:42 UTC, stonebuzz commented
Fixed with last commit, 

The first version of this fix only managed fields of type ```Dropdown-XXX```, now this PR also manages fields of type ```dropdown```.

2024-02-02 10:44 UTC, AdrienClairembault approved these changes

2024-02-08 08:13 UTC, AdrienClairembault approved these changes

2024-02-09 09:00 UTC, merged