(fix) Strpslashes log error
pluginsGLPI/fields pull request #802
Opened 2024-07-01 08:38 UTC by Lainow

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | !33520

When filling in a RichText field for the first time, an error appears on the screen.
![image](https://github.com/pluginsGLPI/fields/assets/107540223/133d1854-014f-4e55-a501-ec7562a6488f)

This is due to the attempt to save data in the _updater_... parameter, which is an array, causing the error.
![image](https://github.com/pluginsGLPI/fields/assets/107540223/78607ec1-28b7-4239-9f85-8fa9cf2cd768)

2024-07-01 10:16 UTC, AdrienClairembault approved these changes

2024-07-01 12:52 UTC, stonebuzz requested changes

2024-07-01 12:52 UTC, stonebuzz commented on inc/container.class.php
> +                if (!empty($value) && strpos($key, '_uploader_') === false) {
```suggestion
                //do not log if value is empty or if dom name is part of file upload
                if (!empty($value) && strpos($key, '_uploader_') === false) {
```

2024-07-01 12:52 UTC, stonebuzz commented
waiting for customer feedback

2024-07-01 13:50 UTC, stonebuzz approved these changes

2024-07-01 13:51 UTC, stonebuzz commented
Customer approves the fixe !33520

2024-07-02 06:01 UTC, trasher approved these changes

2024-07-02 06:14 UTC, stonebuzz commented
@Lainow can you complete the CHANGELOG ?

2024-07-02 14:09 UTC, stonebuzz commented
can you rebase ?

2024-07-03 09:39 UTC, merged