(fix) Update item date_mod
pluginsGLPI/fields pull request #803
Opened 2024-07-01 11:40 UTC by Lainow

| Q             | A
| ------------- | ---
| Bug fix?      | yes
| New feature?  | no
| BC breaks?    | no
| Deprecations? | no
| Tests pass?   | yes
| Fixed tickets | !33527

After modifying additional fields, the modification date is not updated.

2024-07-01 12:47 UTC, stonebuzz requested changes

2024-07-01 12:48 UTC, stonebuzz requested changes

2024-07-01 12:48 UTC, stonebuzz commented on inc/container.class.php
> +                $item->input['date_mod'] = date("Y-m-d H:i:s");
```suggestion
                $item->input['date_mod'] = $_SESSION["glpi_currenttime"];
```

2024-07-01 14:08 UTC, AdrienClairembault reviewed
This is weird because GLPI core is already supposed to do it:

![image](https://github.com/pluginsGLPI/fields/assets/42734840/05e26a2e-cfb5-496b-9658-93cbe5ef092a)

2024-07-02 06:41 UTC, stonebuzz commented
@Lainow can you complete the CHANGELOG ?

2024-07-02 06:41 UTC, stonebuzz commented
> This is weird because GLPI core is already supposed to do it:
> 
> ![image](https://private-user-images.githubusercontent.com/42734840/344707025-05e26a2e-cfb5-496b-9658-93cbe5ef092a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5MDI3NzMsIm5iZiI6MTcxOTkwMjQ3MywicGF0aCI6Ii80MjczNDg0MC8zNDQ3MDcwMjUtMDVlMjZhMmUtY2ZiNS00OTZiLTk2NTgtOTNjYmU1ZWYwOTJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAyVDA2NDExM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyMzlmNzA1ODQ1OTk0MWIyNDgwNDg3NzVkYTZhNzhkZjY3OGYyZWNjZDY0ZjY3ZWY2ODRkYzJlMTQ1MzAxZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DfY1SCZ0YqWc2aGsscVDmEndBvPZXQq7PH70sS47mlM)

only for objects which have a 'date_mod' field and which are affected by the update.

In this case, it is the data from the fields plugin that is updated and not the linked GLPI object (so ```$this->updates``` contains nothing for the GLPI object).

2024-07-02 07:37 UTC, AdrienClairembault commented
> > This is weird because GLPI core is already supposed to do it:
> > ![image](https://private-user-images.githubusercontent.com/42734840/344707025-05e26a2e-cfb5-496b-9658-93cbe5ef092a.png?jwt=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJnaXRodWIuY29tIiwiYXVkIjoicmF3LmdpdGh1YnVzZXJjb250ZW50LmNvbSIsImtleSI6ImtleTUiLCJleHAiOjE3MTk5MDI3NzMsIm5iZiI6MTcxOTkwMjQ3MywicGF0aCI6Ii80MjczNDg0MC8zNDQ3MDcwMjUtMDVlMjZhMmUtY2ZiNS00OTZiLTk2NTgtOTNjYmU1ZWYwOTJhLnBuZz9YLUFtei1BbGdvcml0aG09QVdTNC1ITUFDLVNIQTI1NiZYLUFtei1DcmVkZW50aWFsPUFLSUFWQ09EWUxTQTUzUFFLNFpBJTJGMjAyNDA3MDIlMkZ1cy1lYXN0LTElMkZzMyUyRmF3czRfcmVxdWVzdCZYLUFtei1EYXRlPTIwMjQwNzAyVDA2NDExM1omWC1BbXotRXhwaXJlcz0zMDAmWC1BbXotU2lnbmF0dXJlPTUyMzlmNzA1ODQ1OTk0MWIyNDgwNDg3NzVkYTZhNzhkZjY3OGYyZWNjZDY0ZjY3ZWY2ODRkYzJlMTQ1MzAxZmQmWC1BbXotU2lnbmVkSGVhZGVycz1ob3N0JmFjdG9yX2lkPTAma2V5X2lkPTAmcmVwb19pZD0wIn0.DfY1SCZ0YqWc2aGsscVDmEndBvPZXQq7PH70sS47mlM)
> 
> only for objects which have a `date_mod` field and which are affected by the update.
> 
> In this case, it is the data from the fields plugin that is updated and not the linked GLPI object (so `$this->updates` contains nothing for the GLPI object).

I see, thanks for this details.
I've actually had the same issue on forms when updating a linked question and used the same solution so ok for me 👍.

2024-07-02 07:38 UTC, AdrienClairembault approved these changes

2024-07-02 13:44 UTC, stonebuzz requested changes

2024-07-02 13:44 UTC, stonebuzz commented on CHANGELOG.md
> +- Update item date_mod after updating additional fields
```suggestion
- Update main item ```date_mod``` after updating additional fields
```

2024-07-02 14:08 UTC, stonebuzz approved these changes

2024-07-02 14:09 UTC, merged