fix: datatype number for search
pluginsGLPI/fields pull request #857
Opened 2024-11-18 13:12 UTC by MyvTsv

- [x] I have performed a self-review of my code.
- [x] I have added tests (when available) that prove my fix is effective or that my feature works.

## Description

- It fixes !35167
- Change the decimal type of number fields to display the decimal part of the decimal numbers in search options

## Screenshots (if appropriate):
![Capture d’écran du 2024-11-18 14-11-57](https://github.com/user-attachments/assets/923b2a11-b6a1-4a39-9386-4e8dbb750a4e)

2024-11-18 14:12 UTC, stonebuzz commented
Does searching with `<` still work?

2024-11-18 14:17 UTC, MyvTsv commented
> Does searching with `<` still work?

Yes the operator is functional

![Capture d’écran du 2024-11-18 15-15-19](https://github.com/user-attachments/assets/9fef9936-27cd-4126-9260-5f4b33b2bced)
![Capture d’écran du 2024-11-18 15-15-11](https://github.com/user-attachments/assets/9529e9df-64db-42f9-9eed-810f0faeb649)

2024-11-18 15:28 UTC, stonebuzz approved these changes

2024-11-18 15:28 UTC, stonebuzz commented
Can you propose a patch to the user to get another validation that it works properly?

2024-11-28 06:58 UTC, Rom1-B requested changes
Seems OK, waiting customer feedback.

2024-12-19 14:33 UTC, Rom1-B approved these changes

2024-12-19 14:33 UTC, stonebuzz commented
@MyvTsv can you adapt ``CHANGELOG.md`

2024-12-26 13:34 UTC, stonebuzz requested changes

2024-12-26 13:34 UTC, stonebuzz commented on CHANGELOG.md
> +- Change the decimal type of number fields to display the decimal part of the decimal numbers in search options.
```suggestion
- Force decimal ‘datatype’ of `numeric` fields  for more accurate display.
```

2024-12-26 14:01 UTC, stonebuzz approved these changes

2024-12-26 14:01 UTC, merged