Fix: API issue preventing multi-field updates
pluginsGLPI/fields pull request #869
Opened 2024-12-11 10:22 UTC by MyvTsv

## Checklist before requesting a review

*Please delete options that are not relevant.*

- [x] I have performed a self-review of my code.

## Description

- It fixes !35540
- It fixes the issue that prevented modifying a field via the API when a field and a new tab were added to the same object.

2024-12-11 10:39 UTC, Rom1-B requested changes

2024-12-11 10:39 UTC, Rom1-B commented on inc/container.class.php
> +                $data = $containerClass;
```suggestion
            foreach ($item->input['_plugin_fields_data'] as $data) {
```

2024-12-11 10:39 UTC, Rom1-B commented on inc/container.class.php
> +        $loc_c = new PluginFieldsContainer();
Please use explicit variable names

2024-12-11 10:48 UTC, stonebuzz requested changes

2024-12-11 10:48 UTC, stonebuzz commented on inc/container.class.php
> +                    $item->input['date_mod'] = $_SESSION['glpi_currenttime'];
You can `exit` from `foreach` here, no need to check for all container if one of them already trigger an update on `date_mod`

2024-12-11 10:48 UTC, stonebuzz commented on inc/container.class.php
> +                }
```suggestion
                if (!$DB->fieldExists(static::getTable(), $key) || false === ($c_id = self::findContainer(get_Class($item), $type, $subtype))) {
                    // tries for 'tab'
                    if (false === ($c_id = self::findContainer(get_Class($item)))) {
                        return false;
                    }
                }
```

2024-12-11 13:09 UTC, stonebuzz commented
@MyvTsv can you adapt `CHANGELOG.md`

2024-12-11 13:19 UTC, Rom1-B requested changes
waiting for customer feedback

2024-12-11 13:51 UTC, stonebuzz requested changes

2024-12-11 13:51 UTC, stonebuzz commented on CHANGELOG.md
> +- Fix issue preventing field modification via API when a field and a new tab are added to the same object
```suggestion
- Fixed a problem with fields being updated if there are several containers on the object.
```

2024-12-19 14:27 UTC, MyvTsv commented
https://github.com/pluginsGLPI/fields/pull/875

2024-12-19 14:28 UTC, closed without merging